#!/usr/bin/env bash

# get the packages we need
yum install -y haproxy
yum install -y firewalld
yum install -y httpd
yum install -y epel-release
yum install -y certbot python2-certbot-apache mod_ssl
yum erase -y podman
yum install -y yum-utils device-mapper-persistent-data lvm2
yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
yum update -y
yum install -y docker

# firewall rules
# docker ports
firewall-cmd --permanent --add-port=2376/tcp
firewall-cmd --permanent --add-port=2377/tcp
firewall-cmd --permanent --add-port=7946/tcp
firewall-cmd --permanent --add-port=7946/udp
firewall-cmd --permanent --add-port=4789/udp
# external registry behind haproxy port
firewall-cmd --permanent --add-port=666/tcp
# web ports
firewall-cmd --permanent --add-port=443/tcp
firewall-cmd --permanent --add-port=80/tcp
# admin ports
firewall-cmd --permanent --add-ports=22/tcp

firewall-cmd --reload


# services
systemctl enable httpd
systemctl enable haproxy
systemctl enable docker
systemctl enable firewalld
