#!/usr/bin/env bash

# check for edits to haproxy.cfg acl
grep ACCESSLISTHERE haproxy.cfg 2>/dev/null && echo "Error: haproxy.cfg has access IP/URL list set to just ACCESSLISTHERE" && echo "replace ACCESSLISTHERE in the haproxy config with a space delimited list of IPs IP ranges, or URLs that will be allowed to access the registry." && exit 1

# get the packages we need
yum install -y haproxy
yum install -y firewalld
yum install -y httpd
yum install -y epel-release
yum install -y certbot python2-certbot-apache mod_ssl
yum erase -y podman
yum install -y yum-utils device-mapper-persistent-data lvm2
yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
yum update -y
yum install -y docker

# firewall rules
# docker ports
firewall-cmd --permanent --add-port=2376/tcp
firewall-cmd --permanent --add-port=2377/tcp
firewall-cmd --permanent --add-port=7946/tcp
firewall-cmd --permanent --add-port=7946/udp
firewall-cmd --permanent --add-port=4789/udp
# external registry behind haproxy port
firewall-cmd --permanent --add-port=666/tcp
# web ports
firewall-cmd --permanent --add-port=443/tcp
firewall-cmd --permanent --add-port=80/tcp
# admin ports
firewall-cmd --permanent --add-ports=22/tcp
firewall-cmd --reload

reglistener=$(docker container ls | awk '{print $2}' | grep registry | wc -l)
if [ $reglistener = 1 ]; then
  echo "local docker registry found..."
else
  echo "No local registry found, starting up local registry."
  docker run -d --restart unless-stopped  -p 127.0.0.1:5000:5000 registry
fi

# services
systemctl enable httpd
systemctl enable haproxy
systemctl enable docker
systemctl enable firewalld
systemctl restart httpd
certbot --apache -d $1 # pass in DNS names and alternate names
mkdir ~/certs
primary=$(echo $1 | cut -d',' -f1)
cp /etc/letsencrypt/live/$primary/* ~/certs/
cat ~/certs/cert.pem ~/certs/chain.pem ~/certs/privkey.pem > /etc/keycert.pem
cp haproxy.cfg /etc/haproxy/haproxy.cfg

systemctl restart haproxy
